server:
  port: 8080

spring:
  application:
    name: AFI-BMSTU-api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://AFI-BMSTU-user-service
          predicates:
            - Path=/api/users/**
        - id: auth-service
          uri: lb://AFI-BMSTU-auth-service
          predicates:
            - Path=/api/auth/**
        - id: event-service
          uri: lb://AFI-BMSTU-event-service
          predicates:
            - Path=/api/admin/**,/api/creator/**,/api/comments/**,/api/events/**,/api/compilations/**,/api/categories/**,/api/requests/**

        # Роуты для Swagger UI
        - id: user-service-swagger
          uri: lb://AFI-BMSTU-user-service
          predicates:
            - Path=/user-service/v3/api-docs
          filters:
            - StripPrefix=1
        - id: auth-service-swagger
          uri: lb://AFI-BMSTU-auth-service
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - StripPrefix=1
        - id: event-service-swagger
          uri: lb://AFI-BMSTU-event-service
          predicates:
            - Path=/event-service/v3/api-docs
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders:
              - Content-Disposition

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER}
    fetch-registry: true
    register-with-eureka: true

springdoc:
  swagger-ui:
    urls:
      - name: auth-service
        url: /auth-service/v3/api-docs
      - name: user-service
        url: /user-service/v3/api-docs
      - name: event-service
        url: /event-service/v3/api-docs